title: Keith's GitHub Blog
author: Keith E Henry
email: keithehenry@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Keith's GitHub Blog about current Coursera classes.
  
# social links
twitter_username: keithehenry
github_username:  keithehenry

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
